import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/Provider'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {




  const supabase = createServerComponentClient({cookies})
  const { data } = await supabase.auth.getSession()

  console.log(data);



  let { data: liked_meals, error } = await supabase
  .from('liked_meals')
  .select('*')

  console.log('====================================');
  console.log(liked_meals);
  console.log('====================================');
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers
        likedMeals={liked_meals}
        session={data}>
          {children}
        </Providers>
      </body>
    </html>
  )
}


// Improvments to make: Search, Less Api calls, types. NO-cache in the do request function.