export const CATEGORIES = [
  'Beef',
  'Chicken',
  'Pork',
  'Seafood',
  'Vegetarian',
  'Vegan',
  'Lamb',
  'Miscellaneous',
  'Dessert',
  'Breakfast',
  'Goat',
  'Starter',
  'Side',
]

export const AREAS = {
  AMERICAN: 'American',
  BRITISH: 'British',
  CANADIAN: 'Canadian',
  CHINESE: 'Chinese',
  DUTCH: 'Dutch',
  EGYPTIAN: 'Egyptian',
  CROATIAN: 'Croatian',
  FRENCH: 'French',
  GREEK: 'Greek',
  INDIAN: 'Indian',
  IRISH: 'Irish',
  ITALIAN: 'Italian',
  JAMAICAN: 'Jamaican',
  JAPANESE: 'Japanese',
  KENYAN: 'Kenyan',
  MALAYSIAN: 'Malaysian',
  MEXICAN: 'Mexican',
  MOROCCAN: 'Moroccan',
  POLISH: 'Polish',
  RUSSIAN: 'Russian',
  SPANISH: 'Spanish',
  THAI: 'Thai',
  TURKISH: 'Turkish',
  TUNISIAN: 'Tunisian',
  VIETNAMESE: 'Vietnamese',
  UKNOWN: 'Unknown',
}

