import { CuisineColors } from "./types";

export const cuisineList: CuisineColors = {
  "American" : "🇺🇸",
  "British" : "🇬🇧",
  "Canadian" : "🇨🇦",
  "Chinese" : "🇨🇳",
  "Croation" : "🇭🇷",
  "Dutch" : "🇳🇱",
  "Egyptian" : "🇪🇬",
  "Filipino" : "🇵🇭",
  "French" : "🇫🇷",
  "Greek" : "🇬🇷",
  "Indian" : "🇮🇳",
  "Irish" : "🇮🇪",
  "Italian" : "🇮🇹",
  "Jamaican" : "🇯🇲",
  "Japanese" : "🇯🇵",
  "Kenyan" : "🇰🇪",
  "Malaysian" : "🇲🇾",
  "Mexican" : "🇲🇽",
  "Moroccan" : "🇲🇦",
  "Polish" : "🇵🇱",
  "Portuguese" : "🇵🇹",
  "Russian" : "🇷🇺",
  "Unknown" : "🤷‍♂️",
  "Vietnamese" : "🇻🇳",
}