const CATEGORIES = {
  BEEF: 'Beef',
  CHICKEN: 'Chicken',
  PORK: 'Pork',
  SEAFOOD: 'Seafood',
  VEGETARIAN: 'Vegetarian',
  VEGAN: 'Vegan',
  LAMB: 'Lamb',
  MISCELLANEOUS: 'Miscellaneous',
  DESSERT: 'Dessert',
  BREAKFAST: 'Breakfast',
  GOAT: 'Goat',
  STARTER: 'Starter',
  SIDE: 'Side',
}

const AREAS = {
  AMERICAN: 'American',
  BRITISH: 'British',
  CANADIAN: 'Canadian',
  CHINESE: 'Chinese',
  DUTCH: 'Dutch',
  EGYPTIAN: 'Egyptian',
  CROATIAN: 'Croatian',
  FRENCH: 'French',
  GREEK: 'Greek',
  INDIAN: 'Indian',
  IRISH: 'Irish',
  ITALIAN: 'Italian',
  JAMAICAN: 'Jamaican',
  JAPANESE: 'Japanese',
  KENYAN: 'Kenyan',
  MALAYSIAN: 'Malaysian',
  MEXICAN: 'Mexican',
  MOROCCAN: 'Moroccan',
  POLISH: 'Polish',
  RUSSIAN: 'Russian',
  SPANISH: 'Spanish',
  THAI: 'Thai',
  TURKISH: 'Turkish',
  TUNISIAN: 'Tunisian',
  VIETNAMESE: 'Vietnamese',
  UKNOWN: 'Unknown',
}

