#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Find and kill the existing Next.js development server process
if lsof -i :3000 | grep LISTEN | awk '{print $2}' | xargs kill -9; then
  echo "Killed existing process on port 3000"
fi

# Start the Next.js development server
yarn dev &

# Wait for the development server to start (you may need to adjust the sleep time)
sleep 10

# Install Cypress dependencies
yarn cypress-install

# Run Cypress tests
yarn cypress run

# Kill the development server
lsof -i :3000 | grep LISTEN | awk '{print $2}' | xargs kill -9
